services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: locadora_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - locadora_network

networks:
  locadora_network:
    external: true
